# Generated by Django 5.0.7 on 2024-09-25 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='name',
            field=models.CharField(default='Site Maintenance Configuration', max_length=100),
        ),
    ]
